name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies for screenshots
        run: sudo apt-get install pngquant optipng

      - name: Init cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Fix NPM permissions
        run: sudo chown -R 1001:118 "/root/.npm"

      - name: Install
        run: |
          npm install
          npx svelte-kit sync
          npx svelte-check --tsconfig ./tsconfig.json

      - name: Lint
        run: npx eslint --color .

      - name: Test Code
        run: npx vitest run --testTimeout 10000

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Test Playwright
        run: npx playwright test

      - name: Build the project
        run: npm run build

      - name: Generate screenshots
        run: npm run screenshots

      - name: Add screenshots to build
        run: mv screenshots build/

      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Generate test coverage
        run: npm run test:coverage

      - name: Upload test coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  page:
    needs: test
    if: github.ref == 'refs/heads/main'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
