name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Init cache
        uses: actions/cache@v4
        with:
          path: "~/.npm\nnode_modules"
          key: cache-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Init cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Fix NPM permissions
        run: sudo chown -R 1001:118 "/root/.npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint codebase
        run: npm run lint

      - name: Format code
        run: npm run format -- --check

      - name: Type check
        run: npm run check

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: npm run test:integration
        env:
          HOME: /root

      - name: Build the project
        run: npm run build
