name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages:
    name: Pages
    uses: ./.github/workflows/pages.yml
